### ISSUE TITLE
Create branch with new requirements for a single node scaling arch

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-server#101]
We had branch for first assumptions. Now we need orbitdb redis cache, ipfs s3, and the api added back in on a branch. Or may be able to just merge into develop now since we have a release timeline.

**Comment by oed** [comment]
I'd like to keep it out of develop for now until we know if we'll deploy the getThread API before or after this.

**Comment by zachferland** [comment]
yeah sounds good
