### ISSUE TITLE
Actually use dotenv

### ISSUE THREAD

**Issue by oed** [3box/3box-pinning-server#24]
Right now we are loading the config from the `.env` file using the `dotenv` library. However we are still using the config defined internally in the pinning-server js file. We need to do `process.env.IPFS_CONF` etc instead of using the constants defined in the file.

**Comment by zachferland** [comment]
Resolved by https://github.com/3box/3box-pinning-server/pull/42

**Comment by oed** [comment]
@zachferland you can use zenhub to attach the PR to the issue!
![image](https://user-images.githubusercontent.com/3909429/50631817-0fe05c00-0f46-11e9-9949-90026a31c604.png)
