### ISSUE TITLE
Decide on path for profile api?

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-server#36]
Currently same as pinning node https://ipfs.3box.io. Where you can make requests at https://ipfs.3box.io/profile or https://ipfs.3box.io/profileList. But maybe we should do something like api.3box.io, ipfs.3box.io/api/, profiles.3box.io etc. Does separate subdomain make configuring other AWS services easier?  But in future if looks anything like https://github.com/3box/3box-pinning-server/pull/23#issuecomment-446620716 then this api could be a lambda func, but depends on what we do for scaling there.

**Comment by michaelsena** [comment]
api.3box.io is nice is we decide this is needed!

**Comment by michaelsena** [comment]
This API will live under api.3box.io/cache/
