### ISSUE TITLE
Automate deployment and setup ports

### ISSUE THREAD

**Issue by oed** [3box/3box-pinning-server#46]
- [x] configuration
- [x] deployment
- [x] creation of endpoints
- [x] general testing

When an update is pushed to **master**:
* Automatically deploy the pinning-server 
* make sure that the ipfs node is available from `ipfs.3box.io`
* make sure that the cache service is availible from `cache.3box.io`

When an update is pushed to **develop**:
* Automatically deploy the pinning-server to a develop instance (completely separate from the master deployment). This likely needs it's own redis config!
* make sure that the ipfs node is available from `ipfs-dev.3box.io`
* make sure that the cache service is availible from `cache-dev.3box.io`

**Comment by c-castillo** [comment]
@oed It's not possible to use `api.3box.io` since amazon reserves it _only for_ lambda services. It can be made available at a different endpoint though.

**Comment by oed** [comment]
@c-castillo ok, let's do `cache.3box.io` & `cache-dev.3box.io`.
