### ISSUE TITLE
Experiment: Run server while using s3 storage layer in ipfs 

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-server#58]
In the repo configs, ipfs allows you pass an instance of different storage backends - https://github.com/ipfs/js-ipfs-repo#setup. An option is the s3 implementation - https://github.com/ipfs/js-datastore-s3. 

For this story, run node with s3 data store. Then setup example run multiple pinning servers with the same data store layer. 

Answer Following questions:
- is s3 datastore lib reliable and mature enough? or at the very least very simple (mitigating any concerns?
- what kinds of problems exist if you run multiple nodes with the same s3 stores? do the locks have to be implemented in  any particular way? if there has to be locks, how slow would that make concurrent writes and reads? In theory im assuming there should not be any lock issues given any two nodes will never by writing to the same key in s3, but practically ipfs may right lock files or something, so maybe in theory possible, but could be too much of a pain to change.

Another story will be to try efs if we see clear areas where that could be better than s3.

**Comment by oed** [comment]
Was thinking about this. How will the storage data of orbitdb be stored? Seems like only storing the ipfs data in s3 will not enable a node to open a store that has been synced by another node and have all the state. We would need to have some kind of shared state for the orbitdb stores also. However this might cause more locking issues?

**Comment by michaelsena** [comment]
This should cover S3 storage for OrbitDB as well.
