### ISSUE TITLE
Experiment: Connect client to multi node backend

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-server#60]
Will the cluster look like a single ipfs node with a single multiaddress to connect to? Does this cause any problems? Or will it look like multiple but can still be routed to any single one.

Small story if the other experimental stories are completed.

Answer Question:Can client connect in same way it does now with single multiaddress? if not, are other solutions practical?

**Comment by zachferland** [comment]
Mostly not concerned now, will be single node id, and look like a single node to anything trying to connect. Packets just routed by l4 or l7 load balancer. But we can still double check once and try once the other stories are completed.

**Comment by michaelsena** [comment]
no longer relevant, likely covered in other scaling stories
