### ISSUE TITLE
Modify Access-Control-Allow-Origin headers for 404 Response 

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-server#70]
We have done this on nginx for 200 responses but not for 404 responses. 

Originally reported by @filips123 here https://github.com/3box/3box-js/issues/300

**Comment by oed** [comment]
Next time we can use the github feature to move the issue 🙂

**Comment by zachferland** [comment]
woah since when was that possible? see the button now hah

**Comment by lsenta** [comment]
Do we have some reference material (source code, documentation, etc) regarding the nginx & servers setup?

**Comment by lsenta** [comment]
We can either:
nginx config, use the `always` flag on headers we add (we use nginx 1.12)
http://nginx.org/en/docs/http/ngx_http_headers_module.html

Or implement everything cors related in the app:
```js
    this.app.use(cors({
      origin: '*',
      methods: ['GET', 'POST', 'OPTIONS'],
      allowedHeaders: [
        'DNT', 'User-Agent', 'X-Requested-With', 'If-Modified-Since',
        'Cache-Control', 'Content-Type', 'Range'
      ],
      exposedHeaders: [
        'Content-Length', 'Content-Range'
      ]
    }))
```

Are we versioning nginx configuration files somewhere?

**Comment by zachferland** [comment]
If i remember we definitely need change nginx config for headers, otherwise even the headers defined in the app may not be relayed through. But I think it is ideal to also set the configs in the app so that if we are running nodes in different env (even locally or without nginx) they work as expected.

We want to version/commit nginx config files somewhere, but at the moment they are not, and something we are looking to manage better as part of new service.

**Comment by jamesmorgan** [comment]
This would be great, I tried integrating 3Box into one of our DApps this morning but failed due to CORS issues when loading profiles. e.g.

```
Access to fetch at 'https://ipfs.3box.io/profile?address=0x0df0cc6576ed17ba870d6fc271e20601e3ee176e' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

All I am doing is the following:

```
Box.getProfile(this.account).then(profile => {
          this.profile = profile;
        });
```

Butting running locally

**Comment by zachferland** [comment]
Thanks @jamesmorgan for the additional report! to add some details, there is only CORS issues on 404 response which are for addresses with no profiles, any address with a profile should return a 200 with expected headers ( no cors issue). 

We will be releasing the fix to this issue within a working day or two, so either way, will work as expected soon

**Comment by lsenta** [comment]
Thanks for the report @jamesmorgan, we deployed the fix today, you should get an error object without a CORS error now.
