### ISSUE TITLE
Remove profile api/cache code/module from the pinning server

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-server#81]
Being moved to separate repo/service

**Comment by lsenta** [comment]
Here's what I understood and a proposition to resolve this:

We have:
- the profile API: `https://ipfs.3box.io/profile?address=0x70`, aka `cacheService.js` that serves a profile kv-store through a REST API
- the cache: aka `cache.js` that caches the orbitdb kv store in Redis
- the pinning code

We want to split these in a way that make sense and can scale.

Proposition:
We take the profile API out of the service, refactor & reuse the code from the 3box-js lib.
This'll give us a new service that is focused on interacting with profiles through REST (only reading for now, could be more in the future).
AFAII, next we'll interact with the data through an s3 store and might share some backend library between pinning & rest services.

<img width="539" alt="screenshot 2019-03-04 at 14 39 06" src="https://user-images.githubusercontent.com/1136669/53736882-49244200-3e8b-11e9-8d47-77ed31064a71.png">

If this is OK, I'll move forward, clone the repo and start splitting the code.

**Comment by oed** [comment]
@lsenta This story is only for removing the cache/profile API from the pinning-server. I don't think it makes sense to actually merge this to production before we are actually using the S3 store which will enable us to create serverless functions that provide the profiles api.
So basically I don't think the "3box-rest" module you are suggesting is needed.
Maybe @zachferland has some additional feedback.

**Comment by lsenta** [comment]
Thanks for the clarification, I didn't had the longer-term vision of moving the profile API to s3 and serverless all at once.
