### ISSUE TITLE
Migrate current ipfs blocks (profile data) from backup to shared data layer.

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-server#84]
We should be able to implement a migration function that takes the data from our backup and writes it to our new store. We could also get the same effect a level up by just simulating users/opening stores on both our pinning node and the new one. Both are probably similar amounts of work, but the first we can get a bit better guarantees. This store is the first attempt at do this, will still need more validation and testing stories in the future before actually moving over.

For this one, the new store and backup may be very similar, making migration simple.

**Comment by zachferland** [comment]
Ok much simpler than expected, mapping fs on pinning node to s3 bucket is very simple. 

example: 
```
 aws s3 jsipfs s3://our-ipfs-bucket/jsipfs
```

I think is an option to also only copy files that don't exist in s3, will add here after.

Had originally thought about more general solution of mapping one js ipfs repo instance to another. But this entirely sufficient for our use case. Was already able to transfer our ipfs data to a s3 bucket and run another node with that bucket.

**Comment by oed** [comment]
Oh, that really sweet!
